apiVersion: v1
kind: Service
metadata:
  name: miracle-payment-svc
  labels:
    app: miracle-payment-svc
spec:
  selector:
    app: miracle-payment-app
  ports:
    - protocol: TCP
      port: 9193
      targetPort: 9193
  type: ClusterIP