apiVersion: v1
kind: Service
metadata:
  name: miracle-main-svc
  labels:
    app: miracle-main-svc
spec:
  selector:
    app: miracle-main-app
  ports:
    - protocol: TCP
      port: 9192
      targetPort: 9192
  type: ClusterIP