apiVersion: v1
kind: Service
metadata:
  name: miracle-client-svc
  labels:
    app: miracle-client-svc
spec:
  selector:
    app: miracle-client-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP