apiVersion: apps/v1
kind: Deployment
metadata:
  name: miracle-client-deploy
spec:
  selector:
    matchLabels:
      app: miracle-client-app
  replicas: 1
  template:
    metadata:
      labels:
        app: miracle-client-app
    spec:
      containers:
        - name: miracle-client-app
          image: keoffor/miracle-client-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080