apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: keoffor/mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - name: mysql-port
              containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-init-config
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-init-config
          configMap:
            name: mysql-init-config
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc-claim

      initContainers:
        - name: busybox
          image: busybox:latest
          args: [ "rm", "-rf", "/var/lib/mysql/lost+found" ]
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql