apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: miracle-backend-route
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - "dev.kenstudy.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: miracle-main-svc
          port: 9192
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: Authorization
                value: "{http.request.header.Authorization}"
    - matches:
        - path:
            type: PathPrefix
            value: "/payment"
      backendRefs:
        - name: miracle-payment-svc
          port: 9193
